server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/schoolsecuritysystem?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: caidaweigo@163.com
    password: CJZQFQEBQYOTOLWB
    port: 25
    protocol: smtp
    default-encoding: utf-8


#  accessKeyId:
#  accessKeySecre:

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml

