package com.schoolSecuritySystem.pojo;


import java.io.Serializable;

public class CarRecord  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.carnumber
     *
     * @mbggenerated
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.carintime
     *
     * @mbggenerated
     */
    private String carintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.carouttime
     *
     * @mbggenerated
     */
    private String carouttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.costmethod
     *
     * @mbggenerated
     */
    private Integer costmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_record.cost
     *
     * @mbggenerated
     */
    private Double cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.id
     *
     * @return the value of car_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.id
     *
     * @param id the value for car_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.carnumber
     *
     * @return the value of car_record.carnumber
     *
     * @mbggenerated
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.carnumber
     *
     * @param carnumber the value for car_record.carnumber
     *
     * @mbggenerated
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.carintime
     *
     * @return the value of car_record.carintime
     *
     * @mbggenerated
     */
    public String getCarintime() {
        return carintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.carintime
     *
     * @param carintime the value for car_record.carintime
     *
     * @mbggenerated
     */
    public void setCarintime(String carintime) {
        this.carintime = carintime == null ? null : carintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.carouttime
     *
     * @return the value of car_record.carouttime
     *
     * @mbggenerated
     */
    public String getCarouttime() {
        return carouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.carouttime
     *
     * @param carouttime the value for car_record.carouttime
     *
     * @mbggenerated
     */
    public void setCarouttime(String carouttime) {
        this.carouttime = carouttime == null ? null : carouttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.status
     *
     * @return the value of car_record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.status
     *
     * @param status the value for car_record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.costmethod
     *
     * @return the value of car_record.costmethod
     *
     * @mbggenerated
     */
    public Integer getCostmethod() {
        return costmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.costmethod
     *
     * @param costmethod the value for car_record.costmethod
     *
     * @mbggenerated
     */
    public void setCostmethod(Integer costmethod) {
        this.costmethod = costmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_record.cost
     *
     * @return the value of car_record.cost
     *
     * @mbggenerated
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_record.cost
     *
     * @param cost the value for car_record.cost
     *
     * @mbggenerated
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", carnumber=").append(carnumber);
        sb.append(", carintime=").append(carintime);
        sb.append(", carouttime=").append(carouttime);
        sb.append(", status=").append(status);
        sb.append(", costmethod=").append(costmethod);
        sb.append(", cost=").append(cost);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}