package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class Carrecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrecord.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrecord.carNumber
     *
     * @mbggenerated
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrecord.carInTime
     *
     * @mbggenerated
     */
    private String carintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrecord.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrecord.carOutTime
     *
     * @mbggenerated
     */
    private String carouttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carrecord
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrecord.id
     *
     * @return the value of carrecord.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrecord.id
     *
     * @param id the value for carrecord.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrecord.carNumber
     *
     * @return the value of carrecord.carNumber
     *
     * @mbggenerated
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrecord.carNumber
     *
     * @param carnumber the value for carrecord.carNumber
     *
     * @mbggenerated
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrecord.carInTime
     *
     * @return the value of carrecord.carInTime
     *
     * @mbggenerated
     */
    public String getCarintime() {
        return carintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrecord.carInTime
     *
     * @param carintime the value for carrecord.carInTime
     *
     * @mbggenerated
     */
    public void setCarintime(String carintime) {
        this.carintime = carintime == null ? null : carintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrecord.status
     *
     * @return the value of carrecord.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrecord.status
     *
     * @param status the value for carrecord.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrecord.carOutTime
     *
     * @return the value of carrecord.carOutTime
     *
     * @mbggenerated
     */
    public String getCarouttime() {
        return carouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrecord.carOutTime
     *
     * @param carouttime the value for carrecord.carOutTime
     *
     * @mbggenerated
     */
    public void setCarouttime(String carouttime) {
        this.carouttime = carouttime == null ? null : carouttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrecord
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", carnumber=").append(carnumber);
        sb.append(", carintime=").append(carintime);
        sb.append(", status=").append(status);
        sb.append(", carouttime=").append(carouttime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}