package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class DiningroomCardInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diningroom_card_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diningroom_card_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diningroom_card_info.IdCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diningroom_card_info.surplus
     *
     * @mbggenerated
     */
    private Double surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diningroom_card_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diningroom_card_info.id
     *
     * @return the value of diningroom_card_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diningroom_card_info.id
     *
     * @param id the value for diningroom_card_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diningroom_card_info.name
     *
     * @return the value of diningroom_card_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diningroom_card_info.name
     *
     * @param name the value for diningroom_card_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diningroom_card_info.IdCard
     *
     * @return the value of diningroom_card_info.IdCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diningroom_card_info.IdCard
     *
     * @param idcard the value for diningroom_card_info.IdCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diningroom_card_info.surplus
     *
     * @return the value of diningroom_card_info.surplus
     *
     * @mbggenerated
     */
    public Double getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diningroom_card_info.surplus
     *
     * @param surplus the value for diningroom_card_info.surplus
     *
     * @mbggenerated
     */
    public void setSurplus(Double surplus) {
        this.surplus = surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diningroom_card_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", idcard=").append(idcard);
        sb.append(", surplus=").append(surplus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}