package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class EmployeeInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.work
     *
     * @mbggenerated
     */
    private String work;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.mobliePhone
     *
     * @mbggenerated
     */
    private String mobliephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.employeeCardId
     *
     * @mbggenerated
     */
    private String employeecardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.emergencyContact
     *
     * @mbggenerated
     */
    private String emergencycontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.emergencyContactMobilePhone
     *
     * @mbggenerated
     */
    private String emergencycontactmobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.role
     *
     * @mbggenerated
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.id
     *
     * @return the value of employee_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.id
     *
     * @param id the value for employee_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.name
     *
     * @return the value of employee_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.name
     *
     * @param name the value for employee_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.gender
     *
     * @return the value of employee_info.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.gender
     *
     * @param gender the value for employee_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.work
     *
     * @return the value of employee_info.work
     *
     * @mbggenerated
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.work
     *
     * @param work the value for employee_info.work
     *
     * @mbggenerated
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.mobliePhone
     *
     * @return the value of employee_info.mobliePhone
     *
     * @mbggenerated
     */
    public String getMobliephone() {
        return mobliephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.mobliePhone
     *
     * @param mobliephone the value for employee_info.mobliePhone
     *
     * @mbggenerated
     */
    public void setMobliephone(String mobliephone) {
        this.mobliephone = mobliephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.employeeCardId
     *
     * @return the value of employee_info.employeeCardId
     *
     * @mbggenerated
     */
    public String getEmployeecardid() {
        return employeecardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.employeeCardId
     *
     * @param employeecardid the value for employee_info.employeeCardId
     *
     * @mbggenerated
     */
    public void setEmployeecardid(String employeecardid) {
        this.employeecardid = employeecardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.address
     *
     * @return the value of employee_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.address
     *
     * @param address the value for employee_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.emergencyContact
     *
     * @return the value of employee_info.emergencyContact
     *
     * @mbggenerated
     */
    public String getEmergencycontact() {
        return emergencycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.emergencyContact
     *
     * @param emergencycontact the value for employee_info.emergencyContact
     *
     * @mbggenerated
     */
    public void setEmergencycontact(String emergencycontact) {
        this.emergencycontact = emergencycontact == null ? null : emergencycontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.emergencyContactMobilePhone
     *
     * @return the value of employee_info.emergencyContactMobilePhone
     *
     * @mbggenerated
     */
    public String getEmergencycontactmobilephone() {
        return emergencycontactmobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.emergencyContactMobilePhone
     *
     * @param emergencycontactmobilephone the value for employee_info.emergencyContactMobilePhone
     *
     * @mbggenerated
     */
    public void setEmergencycontactmobilephone(String emergencycontactmobilephone) {
        this.emergencycontactmobilephone = emergencycontactmobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.Email
     *
     * @return the value of employee_info.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.Email
     *
     * @param email the value for employee_info.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.role
     *
     * @return the value of employee_info.role
     *
     * @mbggenerated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.role
     *
     * @param role the value for employee_info.role
     *
     * @mbggenerated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", work=").append(work);
        sb.append(", mobliephone=").append(mobliephone);
        sb.append(", employeecardid=").append(employeecardid);
        sb.append(", address=").append(address);
        sb.append(", emergencycontact=").append(emergencycontact);
        sb.append(", emergencycontactmobilephone=").append(emergencycontactmobilephone);
        sb.append(", email=").append(email);
        sb.append(", role=").append(role);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}