package com.schoolSecuritySystem.pojo;

import java.util.ArrayList;
import java.util.List;

public class EntranceGuardInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public EntranceGuardInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberIsNull() {
            addCriterion("entrance_guard_number is null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberIsNotNull() {
            addCriterion("entrance_guard_number is not null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberEqualTo(String value) {
            addCriterion("entrance_guard_number =", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotEqualTo(String value) {
            addCriterion("entrance_guard_number <>", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberGreaterThan(String value) {
            addCriterion("entrance_guard_number >", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("entrance_guard_number >=", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberLessThan(String value) {
            addCriterion("entrance_guard_number <", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberLessThanOrEqualTo(String value) {
            addCriterion("entrance_guard_number <=", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberLike(String value) {
            addCriterion("entrance_guard_number like", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotLike(String value) {
            addCriterion("entrance_guard_number not like", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberIn(List<String> values) {
            addCriterion("entrance_guard_number in", values, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotIn(List<String> values) {
            addCriterion("entrance_guard_number not in", values, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberBetween(String value1, String value2) {
            addCriterion("entrance_guard_number between", value1, value2, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotBetween(String value1, String value2) {
            addCriterion("entrance_guard_number not between", value1, value2, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressIsNull() {
            addCriterion("entrance_guard_address is null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressIsNotNull() {
            addCriterion("entrance_guard_address is not null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressEqualTo(String value) {
            addCriterion("entrance_guard_address =", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressNotEqualTo(String value) {
            addCriterion("entrance_guard_address <>", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressGreaterThan(String value) {
            addCriterion("entrance_guard_address >", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressGreaterThanOrEqualTo(String value) {
            addCriterion("entrance_guard_address >=", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressLessThan(String value) {
            addCriterion("entrance_guard_address <", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressLessThanOrEqualTo(String value) {
            addCriterion("entrance_guard_address <=", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressLike(String value) {
            addCriterion("entrance_guard_address like", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressNotLike(String value) {
            addCriterion("entrance_guard_address not like", value, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressIn(List<String> values) {
            addCriterion("entrance_guard_address in", values, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressNotIn(List<String> values) {
            addCriterion("entrance_guard_address not in", values, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressBetween(String value1, String value2) {
            addCriterion("entrance_guard_address between", value1, value2, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardAddressNotBetween(String value1, String value2) {
            addCriterion("entrance_guard_address not between", value1, value2, "entranceGuardAddress");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseIsNull() {
            addCriterion("entrance_guard_response is null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseIsNotNull() {
            addCriterion("entrance_guard_response is not null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseEqualTo(String value) {
            addCriterion("entrance_guard_response =", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseNotEqualTo(String value) {
            addCriterion("entrance_guard_response <>", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseGreaterThan(String value) {
            addCriterion("entrance_guard_response >", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseGreaterThanOrEqualTo(String value) {
            addCriterion("entrance_guard_response >=", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseLessThan(String value) {
            addCriterion("entrance_guard_response <", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseLessThanOrEqualTo(String value) {
            addCriterion("entrance_guard_response <=", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseLike(String value) {
            addCriterion("entrance_guard_response like", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseNotLike(String value) {
            addCriterion("entrance_guard_response not like", value, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseIn(List<String> values) {
            addCriterion("entrance_guard_response in", values, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseNotIn(List<String> values) {
            addCriterion("entrance_guard_response not in", values, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseBetween(String value1, String value2) {
            addCriterion("entrance_guard_response between", value1, value2, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardResponseNotBetween(String value1, String value2) {
            addCriterion("entrance_guard_response not between", value1, value2, "entranceGuardResponse");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusIsNull() {
            addCriterion("entrance_guard_status is null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusIsNotNull() {
            addCriterion("entrance_guard_status is not null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusEqualTo(String value) {
            addCriterion("entrance_guard_status =", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusNotEqualTo(String value) {
            addCriterion("entrance_guard_status <>", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusGreaterThan(String value) {
            addCriterion("entrance_guard_status >", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusGreaterThanOrEqualTo(String value) {
            addCriterion("entrance_guard_status >=", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusLessThan(String value) {
            addCriterion("entrance_guard_status <", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusLessThanOrEqualTo(String value) {
            addCriterion("entrance_guard_status <=", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusLike(String value) {
            addCriterion("entrance_guard_status like", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusNotLike(String value) {
            addCriterion("entrance_guard_status not like", value, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusIn(List<String> values) {
            addCriterion("entrance_guard_status in", values, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusNotIn(List<String> values) {
            addCriterion("entrance_guard_status not in", values, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusBetween(String value1, String value2) {
            addCriterion("entrance_guard_status between", value1, value2, "entranceGuardStatus");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardStatusNotBetween(String value1, String value2) {
            addCriterion("entrance_guard_status not between", value1, value2, "entranceGuardStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrance_guard_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}