package com.schoolSecuritySystem.pojo;

import java.util.ArrayList;
import java.util.List;

public class EntranceGuardUserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public EntranceGuardUserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdIsNull() {
            addCriterion("entrance_guard_id is null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdIsNotNull() {
            addCriterion("entrance_guard_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdEqualTo(String value) {
            addCriterion("entrance_guard_id =", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdNotEqualTo(String value) {
            addCriterion("entrance_guard_id <>", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdGreaterThan(String value) {
            addCriterion("entrance_guard_id >", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdGreaterThanOrEqualTo(String value) {
            addCriterion("entrance_guard_id >=", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdLessThan(String value) {
            addCriterion("entrance_guard_id <", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdLessThanOrEqualTo(String value) {
            addCriterion("entrance_guard_id <=", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdLike(String value) {
            addCriterion("entrance_guard_id like", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdNotLike(String value) {
            addCriterion("entrance_guard_id not like", value, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdIn(List<String> values) {
            addCriterion("entrance_guard_id in", values, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdNotIn(List<String> values) {
            addCriterion("entrance_guard_id not in", values, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdBetween(String value1, String value2) {
            addCriterion("entrance_guard_id between", value1, value2, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardIdNotBetween(String value1, String value2) {
            addCriterion("entrance_guard_id not between", value1, value2, "entranceGuardId");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberIsNull() {
            addCriterion("entrance_guard_number is null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberIsNotNull() {
            addCriterion("entrance_guard_number is not null");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberEqualTo(String value) {
            addCriterion("entrance_guard_number =", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotEqualTo(String value) {
            addCriterion("entrance_guard_number <>", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberGreaterThan(String value) {
            addCriterion("entrance_guard_number >", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("entrance_guard_number >=", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberLessThan(String value) {
            addCriterion("entrance_guard_number <", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberLessThanOrEqualTo(String value) {
            addCriterion("entrance_guard_number <=", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberLike(String value) {
            addCriterion("entrance_guard_number like", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotLike(String value) {
            addCriterion("entrance_guard_number not like", value, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberIn(List<String> values) {
            addCriterion("entrance_guard_number in", values, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotIn(List<String> values) {
            addCriterion("entrance_guard_number not in", values, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberBetween(String value1, String value2) {
            addCriterion("entrance_guard_number between", value1, value2, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andEntranceGuardNumberNotBetween(String value1, String value2) {
            addCriterion("entrance_guard_number not between", value1, value2, "entranceGuardNumber");
            return (Criteria) this;
        }

        public Criteria andUserCardidIsNull() {
            addCriterion("user_cardId is null");
            return (Criteria) this;
        }

        public Criteria andUserCardidIsNotNull() {
            addCriterion("user_cardId is not null");
            return (Criteria) this;
        }

        public Criteria andUserCardidEqualTo(String value) {
            addCriterion("user_cardId =", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidNotEqualTo(String value) {
            addCriterion("user_cardId <>", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidGreaterThan(String value) {
            addCriterion("user_cardId >", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidGreaterThanOrEqualTo(String value) {
            addCriterion("user_cardId >=", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidLessThan(String value) {
            addCriterion("user_cardId <", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidLessThanOrEqualTo(String value) {
            addCriterion("user_cardId <=", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidLike(String value) {
            addCriterion("user_cardId like", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidNotLike(String value) {
            addCriterion("user_cardId not like", value, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidIn(List<String> values) {
            addCriterion("user_cardId in", values, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidNotIn(List<String> values) {
            addCriterion("user_cardId not in", values, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidBetween(String value1, String value2) {
            addCriterion("user_cardId between", value1, value2, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserCardidNotBetween(String value1, String value2) {
            addCriterion("user_cardId not between", value1, value2, "userCardid");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserRoleIsNull() {
            addCriterion("user_role is null");
            return (Criteria) this;
        }

        public Criteria andUserRoleIsNotNull() {
            addCriterion("user_role is not null");
            return (Criteria) this;
        }

        public Criteria andUserRoleEqualTo(String value) {
            addCriterion("user_role =", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotEqualTo(String value) {
            addCriterion("user_role <>", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleGreaterThan(String value) {
            addCriterion("user_role >", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleGreaterThanOrEqualTo(String value) {
            addCriterion("user_role >=", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLessThan(String value) {
            addCriterion("user_role <", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLessThanOrEqualTo(String value) {
            addCriterion("user_role <=", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleLike(String value) {
            addCriterion("user_role like", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotLike(String value) {
            addCriterion("user_role not like", value, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleIn(List<String> values) {
            addCriterion("user_role in", values, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotIn(List<String> values) {
            addCriterion("user_role not in", values, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleBetween(String value1, String value2) {
            addCriterion("user_role between", value1, value2, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserRoleNotBetween(String value1, String value2) {
            addCriterion("user_role not between", value1, value2, "userRole");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNull() {
            addCriterion("user_mobile is null");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNotNull() {
            addCriterion("user_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobileEqualTo(String value) {
            addCriterion("user_mobile =", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotEqualTo(String value) {
            addCriterion("user_mobile <>", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThan(String value) {
            addCriterion("user_mobile >", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThanOrEqualTo(String value) {
            addCriterion("user_mobile >=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThan(String value) {
            addCriterion("user_mobile <", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThanOrEqualTo(String value) {
            addCriterion("user_mobile <=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLike(String value) {
            addCriterion("user_mobile like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotLike(String value) {
            addCriterion("user_mobile not like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileIn(List<String> values) {
            addCriterion("user_mobile in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotIn(List<String> values) {
            addCriterion("user_mobile not in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileBetween(String value1, String value2) {
            addCriterion("user_mobile between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotBetween(String value1, String value2) {
            addCriterion("user_mobile not between", value1, value2, "userMobile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}