package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class EntranceGuardInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_info.entrance_guard_number
     *
     * @mbggenerated
     */
    private String entranceGuardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_info.entrance_guard_address
     *
     * @mbggenerated
     */
    private String entranceGuardAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_info.entrance_guard_response
     *
     * @mbggenerated
     */
    private String entranceGuardResponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_info.entrance_guard_status
     *
     * @mbggenerated
     */
    private String entranceGuardStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_info.id
     *
     * @return the value of entrance_guard_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_info.id
     *
     * @param id the value for entrance_guard_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_info.entrance_guard_number
     *
     * @return the value of entrance_guard_info.entrance_guard_number
     *
     * @mbggenerated
     */
    public String getEntranceGuardNumber() {
        return entranceGuardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_info.entrance_guard_number
     *
     * @param entranceGuardNumber the value for entrance_guard_info.entrance_guard_number
     *
     * @mbggenerated
     */
    public void setEntranceGuardNumber(String entranceGuardNumber) {
        this.entranceGuardNumber = entranceGuardNumber == null ? null : entranceGuardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_info.entrance_guard_address
     *
     * @return the value of entrance_guard_info.entrance_guard_address
     *
     * @mbggenerated
     */
    public String getEntranceGuardAddress() {
        return entranceGuardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_info.entrance_guard_address
     *
     * @param entranceGuardAddress the value for entrance_guard_info.entrance_guard_address
     *
     * @mbggenerated
     */
    public void setEntranceGuardAddress(String entranceGuardAddress) {
        this.entranceGuardAddress = entranceGuardAddress == null ? null : entranceGuardAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_info.entrance_guard_response
     *
     * @return the value of entrance_guard_info.entrance_guard_response
     *
     * @mbggenerated
     */
    public String getEntranceGuardResponse() {
        return entranceGuardResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_info.entrance_guard_response
     *
     * @param entranceGuardResponse the value for entrance_guard_info.entrance_guard_response
     *
     * @mbggenerated
     */
    public void setEntranceGuardResponse(String entranceGuardResponse) {
        this.entranceGuardResponse = entranceGuardResponse == null ? null : entranceGuardResponse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_info.entrance_guard_status
     *
     * @return the value of entrance_guard_info.entrance_guard_status
     *
     * @mbggenerated
     */
    public String getEntranceGuardStatus() {
        return entranceGuardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_info.entrance_guard_status
     *
     * @param entranceGuardStatus the value for entrance_guard_info.entrance_guard_status
     *
     * @mbggenerated
     */
    public void setEntranceGuardStatus(String entranceGuardStatus) {
        this.entranceGuardStatus = entranceGuardStatus == null ? null : entranceGuardStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entranceGuardNumber=").append(entranceGuardNumber);
        sb.append(", entranceGuardAddress=").append(entranceGuardAddress);
        sb.append(", entranceGuardResponse=").append(entranceGuardResponse);
        sb.append(", entranceGuardStatus=").append(entranceGuardStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}