package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class EntranceGuardUserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.entrance_guard_id
     *
     * @mbggenerated
     */
    private String entranceGuardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.entrance_guard_number
     *
     * @mbggenerated
     */
    private String entranceGuardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.user_cardId
     *
     * @mbggenerated
     */
    private String userCardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.user_role
     *
     * @mbggenerated
     */
    private String userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrance_guard_user_info.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.id
     *
     * @return the value of entrance_guard_user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.id
     *
     * @param id the value for entrance_guard_user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.entrance_guard_id
     *
     * @return the value of entrance_guard_user_info.entrance_guard_id
     *
     * @mbggenerated
     */
    public String getEntranceGuardId() {
        return entranceGuardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.entrance_guard_id
     *
     * @param entranceGuardId the value for entrance_guard_user_info.entrance_guard_id
     *
     * @mbggenerated
     */
    public void setEntranceGuardId(String entranceGuardId) {
        this.entranceGuardId = entranceGuardId == null ? null : entranceGuardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.entrance_guard_number
     *
     * @return the value of entrance_guard_user_info.entrance_guard_number
     *
     * @mbggenerated
     */
    public String getEntranceGuardNumber() {
        return entranceGuardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.entrance_guard_number
     *
     * @param entranceGuardNumber the value for entrance_guard_user_info.entrance_guard_number
     *
     * @mbggenerated
     */
    public void setEntranceGuardNumber(String entranceGuardNumber) {
        this.entranceGuardNumber = entranceGuardNumber == null ? null : entranceGuardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.user_cardId
     *
     * @return the value of entrance_guard_user_info.user_cardId
     *
     * @mbggenerated
     */
    public String getUserCardid() {
        return userCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.user_cardId
     *
     * @param userCardid the value for entrance_guard_user_info.user_cardId
     *
     * @mbggenerated
     */
    public void setUserCardid(String userCardid) {
        this.userCardid = userCardid == null ? null : userCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.user_name
     *
     * @return the value of entrance_guard_user_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.user_name
     *
     * @param userName the value for entrance_guard_user_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.user_role
     *
     * @return the value of entrance_guard_user_info.user_role
     *
     * @mbggenerated
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.user_role
     *
     * @param userRole the value for entrance_guard_user_info.user_role
     *
     * @mbggenerated
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrance_guard_user_info.user_mobile
     *
     * @return the value of entrance_guard_user_info.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrance_guard_user_info.user_mobile
     *
     * @param userMobile the value for entrance_guard_user_info.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entranceGuardId=").append(entranceGuardId);
        sb.append(", entranceGuardNumber=").append(entranceGuardNumber);
        sb.append(", userCardid=").append(userCardid);
        sb.append(", userName=").append(userName);
        sb.append(", userRole=").append(userRole);
        sb.append(", userMobile=").append(userMobile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}