package com.schoolSecuritySystem.pojo;

import java.util.ArrayList;
import java.util.List;

public class EquipmentInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public EquipmentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberIsNull() {
            addCriterion("equipmentNumber is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberIsNotNull() {
            addCriterion("equipmentNumber is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberEqualTo(String value) {
            addCriterion("equipmentNumber =", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberNotEqualTo(String value) {
            addCriterion("equipmentNumber <>", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberGreaterThan(String value) {
            addCriterion("equipmentNumber >", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentNumber >=", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberLessThan(String value) {
            addCriterion("equipmentNumber <", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberLessThanOrEqualTo(String value) {
            addCriterion("equipmentNumber <=", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberLike(String value) {
            addCriterion("equipmentNumber like", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberNotLike(String value) {
            addCriterion("equipmentNumber not like", value, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberIn(List<String> values) {
            addCriterion("equipmentNumber in", values, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberNotIn(List<String> values) {
            addCriterion("equipmentNumber not in", values, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberBetween(String value1, String value2) {
            addCriterion("equipmentNumber between", value1, value2, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmentnumberNotBetween(String value1, String value2) {
            addCriterion("equipmentNumber not between", value1, value2, "equipmentnumber");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeIsNull() {
            addCriterion("equipmentType is null");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeIsNotNull() {
            addCriterion("equipmentType is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeEqualTo(String value) {
            addCriterion("equipmentType =", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeNotEqualTo(String value) {
            addCriterion("equipmentType <>", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeGreaterThan(String value) {
            addCriterion("equipmentType >", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentType >=", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeLessThan(String value) {
            addCriterion("equipmentType <", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeLessThanOrEqualTo(String value) {
            addCriterion("equipmentType <=", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeLike(String value) {
            addCriterion("equipmentType like", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeNotLike(String value) {
            addCriterion("equipmentType not like", value, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeIn(List<String> values) {
            addCriterion("equipmentType in", values, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeNotIn(List<String> values) {
            addCriterion("equipmentType not in", values, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeBetween(String value1, String value2) {
            addCriterion("equipmentType between", value1, value2, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmenttypeNotBetween(String value1, String value2) {
            addCriterion("equipmentType not between", value1, value2, "equipmenttype");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusIsNull() {
            addCriterion("equipmentStatus is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusIsNotNull() {
            addCriterion("equipmentStatus is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusEqualTo(String value) {
            addCriterion("equipmentStatus =", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusNotEqualTo(String value) {
            addCriterion("equipmentStatus <>", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusGreaterThan(String value) {
            addCriterion("equipmentStatus >", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentStatus >=", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusLessThan(String value) {
            addCriterion("equipmentStatus <", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusLessThanOrEqualTo(String value) {
            addCriterion("equipmentStatus <=", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusLike(String value) {
            addCriterion("equipmentStatus like", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusNotLike(String value) {
            addCriterion("equipmentStatus not like", value, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusIn(List<String> values) {
            addCriterion("equipmentStatus in", values, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusNotIn(List<String> values) {
            addCriterion("equipmentStatus not in", values, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusBetween(String value1, String value2) {
            addCriterion("equipmentStatus between", value1, value2, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentstatusNotBetween(String value1, String value2) {
            addCriterion("equipmentStatus not between", value1, value2, "equipmentstatus");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupIsNull() {
            addCriterion("equipmentGroup is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupIsNotNull() {
            addCriterion("equipmentGroup is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupEqualTo(String value) {
            addCriterion("equipmentGroup =", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupNotEqualTo(String value) {
            addCriterion("equipmentGroup <>", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupGreaterThan(String value) {
            addCriterion("equipmentGroup >", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupGreaterThanOrEqualTo(String value) {
            addCriterion("equipmentGroup >=", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupLessThan(String value) {
            addCriterion("equipmentGroup <", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupLessThanOrEqualTo(String value) {
            addCriterion("equipmentGroup <=", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupLike(String value) {
            addCriterion("equipmentGroup like", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupNotLike(String value) {
            addCriterion("equipmentGroup not like", value, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupIn(List<String> values) {
            addCriterion("equipmentGroup in", values, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupNotIn(List<String> values) {
            addCriterion("equipmentGroup not in", values, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupBetween(String value1, String value2) {
            addCriterion("equipmentGroup between", value1, value2, "equipmentgroup");
            return (Criteria) this;
        }

        public Criteria andEquipmentgroupNotBetween(String value1, String value2) {
            addCriterion("equipmentGroup not between", value1, value2, "equipmentgroup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}