package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class EquipmentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.equipmentNumber
     *
     * @mbggenerated
     */
    private String equipmentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.equipmentType
     *
     * @mbggenerated
     */
    private String equipmenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.equipmentStatus
     *
     * @mbggenerated
     */
    private String equipmentstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment_info.equipmentGroup
     *
     * @mbggenerated
     */
    private String equipmentgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.id
     *
     * @return the value of equipment_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.id
     *
     * @param id the value for equipment_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.equipmentNumber
     *
     * @return the value of equipment_info.equipmentNumber
     *
     * @mbggenerated
     */
    public String getEquipmentnumber() {
        return equipmentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.equipmentNumber
     *
     * @param equipmentnumber the value for equipment_info.equipmentNumber
     *
     * @mbggenerated
     */
    public void setEquipmentnumber(String equipmentnumber) {
        this.equipmentnumber = equipmentnumber == null ? null : equipmentnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.equipmentType
     *
     * @return the value of equipment_info.equipmentType
     *
     * @mbggenerated
     */
    public String getEquipmenttype() {
        return equipmenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.equipmentType
     *
     * @param equipmenttype the value for equipment_info.equipmentType
     *
     * @mbggenerated
     */
    public void setEquipmenttype(String equipmenttype) {
        this.equipmenttype = equipmenttype == null ? null : equipmenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.equipmentStatus
     *
     * @return the value of equipment_info.equipmentStatus
     *
     * @mbggenerated
     */
    public String getEquipmentstatus() {
        return equipmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.equipmentStatus
     *
     * @param equipmentstatus the value for equipment_info.equipmentStatus
     *
     * @mbggenerated
     */
    public void setEquipmentstatus(String equipmentstatus) {
        this.equipmentstatus = equipmentstatus == null ? null : equipmentstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_info.equipmentGroup
     *
     * @return the value of equipment_info.equipmentGroup
     *
     * @mbggenerated
     */
    public String getEquipmentgroup() {
        return equipmentgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_info.equipmentGroup
     *
     * @param equipmentgroup the value for equipment_info.equipmentGroup
     *
     * @mbggenerated
     */
    public void setEquipmentgroup(String equipmentgroup) {
        this.equipmentgroup = equipmentgroup == null ? null : equipmentgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", equipmentnumber=").append(equipmentnumber);
        sb.append(", equipmenttype=").append(equipmenttype);
        sb.append(", equipmentstatus=").append(equipmentstatus);
        sb.append(", equipmentgroup=").append(equipmentgroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}