package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class StudentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.academy
     *
     * @mbggenerated
     */
    private String academy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.classroom
     *
     * @mbggenerated
     */
    private String classroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.mobliePhone
     *
     * @mbggenerated
     */
    private String mobliephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.studentCardId
     *
     * @mbggenerated
     */
    private String studentcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.domitory
     *
     * @mbggenerated
     */
    private Integer domitory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.emergencyContact
     *
     * @mbggenerated
     */
    private String emergencycontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.emergencyContactMobilePhone
     *
     * @mbggenerated
     */
    private String emergencycontactmobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.role
     *
     * @mbggenerated
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.id
     *
     * @return the value of student_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.id
     *
     * @param id the value for student_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.name
     *
     * @return the value of student_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.name
     *
     * @param name the value for student_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.gender
     *
     * @return the value of student_info.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.gender
     *
     * @param gender the value for student_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.academy
     *
     * @return the value of student_info.academy
     *
     * @mbggenerated
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.academy
     *
     * @param academy the value for student_info.academy
     *
     * @mbggenerated
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.classroom
     *
     * @return the value of student_info.classroom
     *
     * @mbggenerated
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.classroom
     *
     * @param classroom the value for student_info.classroom
     *
     * @mbggenerated
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.mobliePhone
     *
     * @return the value of student_info.mobliePhone
     *
     * @mbggenerated
     */
    public String getMobliephone() {
        return mobliephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.mobliePhone
     *
     * @param mobliephone the value for student_info.mobliePhone
     *
     * @mbggenerated
     */
    public void setMobliephone(String mobliephone) {
        this.mobliephone = mobliephone == null ? null : mobliephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.studentCardId
     *
     * @return the value of student_info.studentCardId
     *
     * @mbggenerated
     */
    public String getStudentcardid() {
        return studentcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.studentCardId
     *
     * @param studentcardid the value for student_info.studentCardId
     *
     * @mbggenerated
     */
    public void setStudentcardid(String studentcardid) {
        this.studentcardid = studentcardid == null ? null : studentcardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.domitory
     *
     * @return the value of student_info.domitory
     *
     * @mbggenerated
     */
    public Integer getDomitory() {
        return domitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.domitory
     *
     * @param domitory the value for student_info.domitory
     *
     * @mbggenerated
     */
    public void setDomitory(Integer domitory) {
        this.domitory = domitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.emergencyContact
     *
     * @return the value of student_info.emergencyContact
     *
     * @mbggenerated
     */
    public String getEmergencycontact() {
        return emergencycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.emergencyContact
     *
     * @param emergencycontact the value for student_info.emergencyContact
     *
     * @mbggenerated
     */
    public void setEmergencycontact(String emergencycontact) {
        this.emergencycontact = emergencycontact == null ? null : emergencycontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.emergencyContactMobilePhone
     *
     * @return the value of student_info.emergencyContactMobilePhone
     *
     * @mbggenerated
     */
    public String getEmergencycontactmobilephone() {
        return emergencycontactmobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.emergencyContactMobilePhone
     *
     * @param emergencycontactmobilephone the value for student_info.emergencyContactMobilePhone
     *
     * @mbggenerated
     */
    public void setEmergencycontactmobilephone(String emergencycontactmobilephone) {
        this.emergencycontactmobilephone = emergencycontactmobilephone == null ? null : emergencycontactmobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.Email
     *
     * @return the value of student_info.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.Email
     *
     * @param email the value for student_info.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.role
     *
     * @return the value of student_info.role
     *
     * @mbggenerated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.role
     *
     * @param role the value for student_info.role
     *
     * @mbggenerated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", academy=").append(academy);
        sb.append(", classroom=").append(classroom);
        sb.append(", mobliephone=").append(mobliephone);
        sb.append(", studentcardid=").append(studentcardid);
        sb.append(", domitory=").append(domitory);
        sb.append(", emergencycontact=").append(emergencycontact);
        sb.append(", emergencycontactmobilephone=").append(emergencycontactmobilephone);
        sb.append(", email=").append(email);
        sb.append(", role=").append(role);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}