package com.schoolSecuritySystem.pojo;

import java.io.Serializable;

public class Visitorapply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.visitorName
     *
     * @mbggenerated
     */
    private String visitorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.visitorTel
     *
     * @mbggenerated
     */
    private String visitortel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.visitorStartTime
     *
     * @mbggenerated
     */
    private String visitorstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.visitorEndTime
     *
     * @mbggenerated
     */
    private String visitorendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.applicantName
     *
     * @mbggenerated
     */
    private String applicantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.applicantTel
     *
     * @mbggenerated
     */
    private String applicanttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.applicantEmail
     *
     * @mbggenerated
     */
    private String applicantemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitorapply.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.id
     *
     * @return the value of visitorapply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.id
     *
     * @param id the value for visitorapply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.visitorName
     *
     * @return the value of visitorapply.visitorName
     *
     * @mbggenerated
     */
    public String getVisitorname() {
        return visitorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.visitorName
     *
     * @param visitorname the value for visitorapply.visitorName
     *
     * @mbggenerated
     */
    public void setVisitorname(String visitorname) {
        this.visitorname = visitorname == null ? null : visitorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.visitorTel
     *
     * @return the value of visitorapply.visitorTel
     *
     * @mbggenerated
     */
    public String getVisitortel() {
        return visitortel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.visitorTel
     *
     * @param visitortel the value for visitorapply.visitorTel
     *
     * @mbggenerated
     */
    public void setVisitortel(String visitortel) {
        this.visitortel = visitortel == null ? null : visitortel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.visitorStartTime
     *
     * @return the value of visitorapply.visitorStartTime
     *
     * @mbggenerated
     */
    public String getVisitorstarttime() {
        return visitorstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.visitorStartTime
     *
     * @param visitorstarttime the value for visitorapply.visitorStartTime
     *
     * @mbggenerated
     */
    public void setVisitorstarttime(String visitorstarttime) {
        this.visitorstarttime = visitorstarttime == null ? null : visitorstarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.visitorEndTime
     *
     * @return the value of visitorapply.visitorEndTime
     *
     * @mbggenerated
     */
    public String getVisitorendtime() {
        return visitorendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.visitorEndTime
     *
     * @param visitorendtime the value for visitorapply.visitorEndTime
     *
     * @mbggenerated
     */
    public void setVisitorendtime(String visitorendtime) {
        this.visitorendtime = visitorendtime == null ? null : visitorendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.applicantName
     *
     * @return the value of visitorapply.applicantName
     *
     * @mbggenerated
     */
    public String getApplicantname() {
        return applicantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.applicantName
     *
     * @param applicantname the value for visitorapply.applicantName
     *
     * @mbggenerated
     */
    public void setApplicantname(String applicantname) {
        this.applicantname = applicantname == null ? null : applicantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.applicantTel
     *
     * @return the value of visitorapply.applicantTel
     *
     * @mbggenerated
     */
    public String getApplicanttel() {
        return applicanttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.applicantTel
     *
     * @param applicanttel the value for visitorapply.applicantTel
     *
     * @mbggenerated
     */
    public void setApplicanttel(String applicanttel) {
        this.applicanttel = applicanttel == null ? null : applicanttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.applicantEmail
     *
     * @return the value of visitorapply.applicantEmail
     *
     * @mbggenerated
     */
    public String getApplicantemail() {
        return applicantemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.applicantEmail
     *
     * @param applicantemail the value for visitorapply.applicantEmail
     *
     * @mbggenerated
     */
    public void setApplicantemail(String applicantemail) {
        this.applicantemail = applicantemail == null ? null : applicantemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitorapply.type
     *
     * @return the value of visitorapply.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitorapply.type
     *
     * @param type the value for visitorapply.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", visitorname=").append(visitorname);
        sb.append(", visitortel=").append(visitortel);
        sb.append(", visitorstarttime=").append(visitorstarttime);
        sb.append(", visitorendtime=").append(visitorendtime);
        sb.append(", applicantname=").append(applicantname);
        sb.append(", applicanttel=").append(applicanttel);
        sb.append(", applicantemail=").append(applicantemail);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}