package com.schoolSecuritySystem.pojo;

import java.util.ArrayList;
import java.util.List;

public class VisitorapplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public VisitorapplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVisitornameIsNull() {
            addCriterion("visitorName is null");
            return (Criteria) this;
        }

        public Criteria andVisitornameIsNotNull() {
            addCriterion("visitorName is not null");
            return (Criteria) this;
        }

        public Criteria andVisitornameEqualTo(String value) {
            addCriterion("visitorName =", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameNotEqualTo(String value) {
            addCriterion("visitorName <>", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameGreaterThan(String value) {
            addCriterion("visitorName >", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameGreaterThanOrEqualTo(String value) {
            addCriterion("visitorName >=", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameLessThan(String value) {
            addCriterion("visitorName <", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameLessThanOrEqualTo(String value) {
            addCriterion("visitorName <=", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameLike(String value) {
            addCriterion("visitorName like", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameNotLike(String value) {
            addCriterion("visitorName not like", value, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameIn(List<String> values) {
            addCriterion("visitorName in", values, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameNotIn(List<String> values) {
            addCriterion("visitorName not in", values, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameBetween(String value1, String value2) {
            addCriterion("visitorName between", value1, value2, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitornameNotBetween(String value1, String value2) {
            addCriterion("visitorName not between", value1, value2, "visitorname");
            return (Criteria) this;
        }

        public Criteria andVisitortelIsNull() {
            addCriterion("visitorTel is null");
            return (Criteria) this;
        }

        public Criteria andVisitortelIsNotNull() {
            addCriterion("visitorTel is not null");
            return (Criteria) this;
        }

        public Criteria andVisitortelEqualTo(String value) {
            addCriterion("visitorTel =", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelNotEqualTo(String value) {
            addCriterion("visitorTel <>", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelGreaterThan(String value) {
            addCriterion("visitorTel >", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelGreaterThanOrEqualTo(String value) {
            addCriterion("visitorTel >=", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelLessThan(String value) {
            addCriterion("visitorTel <", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelLessThanOrEqualTo(String value) {
            addCriterion("visitorTel <=", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelLike(String value) {
            addCriterion("visitorTel like", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelNotLike(String value) {
            addCriterion("visitorTel not like", value, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelIn(List<String> values) {
            addCriterion("visitorTel in", values, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelNotIn(List<String> values) {
            addCriterion("visitorTel not in", values, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelBetween(String value1, String value2) {
            addCriterion("visitorTel between", value1, value2, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitortelNotBetween(String value1, String value2) {
            addCriterion("visitorTel not between", value1, value2, "visitortel");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeIsNull() {
            addCriterion("visitorStartTime is null");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeIsNotNull() {
            addCriterion("visitorStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeEqualTo(String value) {
            addCriterion("visitorStartTime =", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeNotEqualTo(String value) {
            addCriterion("visitorStartTime <>", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeGreaterThan(String value) {
            addCriterion("visitorStartTime >", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeGreaterThanOrEqualTo(String value) {
            addCriterion("visitorStartTime >=", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeLessThan(String value) {
            addCriterion("visitorStartTime <", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeLessThanOrEqualTo(String value) {
            addCriterion("visitorStartTime <=", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeLike(String value) {
            addCriterion("visitorStartTime like", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeNotLike(String value) {
            addCriterion("visitorStartTime not like", value, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeIn(List<String> values) {
            addCriterion("visitorStartTime in", values, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeNotIn(List<String> values) {
            addCriterion("visitorStartTime not in", values, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeBetween(String value1, String value2) {
            addCriterion("visitorStartTime between", value1, value2, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorstarttimeNotBetween(String value1, String value2) {
            addCriterion("visitorStartTime not between", value1, value2, "visitorstarttime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeIsNull() {
            addCriterion("visitorEndTime is null");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeIsNotNull() {
            addCriterion("visitorEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeEqualTo(String value) {
            addCriterion("visitorEndTime =", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeNotEqualTo(String value) {
            addCriterion("visitorEndTime <>", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeGreaterThan(String value) {
            addCriterion("visitorEndTime >", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeGreaterThanOrEqualTo(String value) {
            addCriterion("visitorEndTime >=", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeLessThan(String value) {
            addCriterion("visitorEndTime <", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeLessThanOrEqualTo(String value) {
            addCriterion("visitorEndTime <=", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeLike(String value) {
            addCriterion("visitorEndTime like", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeNotLike(String value) {
            addCriterion("visitorEndTime not like", value, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeIn(List<String> values) {
            addCriterion("visitorEndTime in", values, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeNotIn(List<String> values) {
            addCriterion("visitorEndTime not in", values, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeBetween(String value1, String value2) {
            addCriterion("visitorEndTime between", value1, value2, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andVisitorendtimeNotBetween(String value1, String value2) {
            addCriterion("visitorEndTime not between", value1, value2, "visitorendtime");
            return (Criteria) this;
        }

        public Criteria andApplicantnameIsNull() {
            addCriterion("applicantName is null");
            return (Criteria) this;
        }

        public Criteria andApplicantnameIsNotNull() {
            addCriterion("applicantName is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantnameEqualTo(String value) {
            addCriterion("applicantName =", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotEqualTo(String value) {
            addCriterion("applicantName <>", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameGreaterThan(String value) {
            addCriterion("applicantName >", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameGreaterThanOrEqualTo(String value) {
            addCriterion("applicantName >=", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameLessThan(String value) {
            addCriterion("applicantName <", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameLessThanOrEqualTo(String value) {
            addCriterion("applicantName <=", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameLike(String value) {
            addCriterion("applicantName like", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotLike(String value) {
            addCriterion("applicantName not like", value, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameIn(List<String> values) {
            addCriterion("applicantName in", values, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotIn(List<String> values) {
            addCriterion("applicantName not in", values, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameBetween(String value1, String value2) {
            addCriterion("applicantName between", value1, value2, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicantnameNotBetween(String value1, String value2) {
            addCriterion("applicantName not between", value1, value2, "applicantname");
            return (Criteria) this;
        }

        public Criteria andApplicanttelIsNull() {
            addCriterion("applicantTel is null");
            return (Criteria) this;
        }

        public Criteria andApplicanttelIsNotNull() {
            addCriterion("applicantTel is not null");
            return (Criteria) this;
        }

        public Criteria andApplicanttelEqualTo(String value) {
            addCriterion("applicantTel =", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelNotEqualTo(String value) {
            addCriterion("applicantTel <>", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelGreaterThan(String value) {
            addCriterion("applicantTel >", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelGreaterThanOrEqualTo(String value) {
            addCriterion("applicantTel >=", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelLessThan(String value) {
            addCriterion("applicantTel <", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelLessThanOrEqualTo(String value) {
            addCriterion("applicantTel <=", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelLike(String value) {
            addCriterion("applicantTel like", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelNotLike(String value) {
            addCriterion("applicantTel not like", value, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelIn(List<String> values) {
            addCriterion("applicantTel in", values, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelNotIn(List<String> values) {
            addCriterion("applicantTel not in", values, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelBetween(String value1, String value2) {
            addCriterion("applicantTel between", value1, value2, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicanttelNotBetween(String value1, String value2) {
            addCriterion("applicantTel not between", value1, value2, "applicanttel");
            return (Criteria) this;
        }

        public Criteria andApplicantemailIsNull() {
            addCriterion("applicantEmail is null");
            return (Criteria) this;
        }

        public Criteria andApplicantemailIsNotNull() {
            addCriterion("applicantEmail is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantemailEqualTo(String value) {
            addCriterion("applicantEmail =", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailNotEqualTo(String value) {
            addCriterion("applicantEmail <>", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailGreaterThan(String value) {
            addCriterion("applicantEmail >", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailGreaterThanOrEqualTo(String value) {
            addCriterion("applicantEmail >=", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailLessThan(String value) {
            addCriterion("applicantEmail <", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailLessThanOrEqualTo(String value) {
            addCriterion("applicantEmail <=", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailLike(String value) {
            addCriterion("applicantEmail like", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailNotLike(String value) {
            addCriterion("applicantEmail not like", value, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailIn(List<String> values) {
            addCriterion("applicantEmail in", values, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailNotIn(List<String> values) {
            addCriterion("applicantEmail not in", values, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailBetween(String value1, String value2) {
            addCriterion("applicantEmail between", value1, value2, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andApplicantemailNotBetween(String value1, String value2) {
            addCriterion("applicantEmail not between", value1, value2, "applicantemail");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visitorapply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}