package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.AddressResponseInfo;
import com.schoolSecuritySystem.pojo.AddressResponseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AddressResponseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int countByExample(AddressResponseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int deleteByExample(AddressResponseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int insert(AddressResponseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int insertSelective(AddressResponseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    List<AddressResponseInfo> selectByExample(AddressResponseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    AddressResponseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AddressResponseInfo record, @Param("example") AddressResponseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AddressResponseInfo record, @Param("example") AddressResponseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AddressResponseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_response_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AddressResponseInfo record);
}