package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.AttenceInfo;
import com.schoolSecuritySystem.pojo.AttenceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AttenceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int countByExample(AttenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int deleteByExample(AttenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int insert(AttenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int insertSelective(AttenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    List<AttenceInfo> selectByExample(AttenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    AttenceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AttenceInfo record, @Param("example") AttenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AttenceInfo record, @Param("example") AttenceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AttenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AttenceInfo record);
}