package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.CarRecord;
import com.schoolSecuritySystem.pojo.CarRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CarRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int countByExample(CarRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int deleteByExample(CarRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int insert(CarRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int insertSelective(CarRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    List<CarRecord> selectByExample(CarRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    CarRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarRecord record, @Param("example") CarRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarRecord record, @Param("example") CarRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarRecord record);
}