package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.EntranceGuardUserInfo;
import com.schoolSecuritySystem.pojo.EntranceGuardUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface EntranceGuardUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int countByExample(EntranceGuardUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int deleteByExample(EntranceGuardUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int insert(EntranceGuardUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int insertSelective(EntranceGuardUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    List<EntranceGuardUserInfo> selectByExample(EntranceGuardUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    EntranceGuardUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EntranceGuardUserInfo record, @Param("example") EntranceGuardUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EntranceGuardUserInfo record, @Param("example") EntranceGuardUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EntranceGuardUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance_guard_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EntranceGuardUserInfo record);
}