package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.InvadeInfo;
import com.schoolSecuritySystem.pojo.InvadeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface InvadeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int countByExample(InvadeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int deleteByExample(InvadeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int insert(InvadeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int insertSelective(InvadeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    List<InvadeInfo> selectByExample(InvadeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    InvadeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InvadeInfo record, @Param("example") InvadeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InvadeInfo record, @Param("example") InvadeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InvadeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invade_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InvadeInfo record);
}