package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.UserCarAccountInfo;
import com.schoolSecuritySystem.pojo.UserCarAccountInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserCarAccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int countByExample(UserCarAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int deleteByExample(UserCarAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int insert(UserCarAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int insertSelective(UserCarAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    List<UserCarAccountInfo> selectByExample(UserCarAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    UserCarAccountInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserCarAccountInfo record, @Param("example") UserCarAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserCarAccountInfo record, @Param("example") UserCarAccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserCarAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_car_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserCarAccountInfo record);
}