package com.schoolSecuritySystem.dao;

import com.schoolSecuritySystem.pojo.Visitorapply;
import com.schoolSecuritySystem.pojo.VisitorapplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorapplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int countByExample(VisitorapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int deleteByExample(VisitorapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int insert(Visitorapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int insertSelective(Visitorapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    List<Visitorapply> selectByExample(VisitorapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    Visitorapply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Visitorapply record, @Param("example") VisitorapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Visitorapply record, @Param("example") VisitorapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Visitorapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorapply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Visitorapply record);
}